name: Main

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build -c Release "src/Hedgehog.Xunit"
    - name: Test F#
      run: dotnet test -c Release "tests/Hedgehog.Xunit.Tests.FSharp" /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Test C#
      run: dotnet test -c Release "tests/Hedgehog.Xunit.Tests.CSharp"
    - name: Run F# Examples
      run: dotnet test -c Release "examples/Hedgehog.Xunit.Examples.FSharp"
    - name: Run C# Examples
      run: dotnet test -c Release "examples/Hedgehog.Xunit.Examples.CSharp"
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: tests/Hedgehog.Xunit.Tests.FSharp/TestResults/coverage.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish NuGet
      uses: alirezanet/publish-nuget@v3.1.0
      with:
        PROJECT_FILE_PATH: "src/Hedgehog.Xunit/Hedgehog.Xunit.fsproj"
        PACKAGE_NAME: "Hedgehog.Xunit"
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
